on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v2
    - uses: testomatio/check-tests@master
      with:
        framework: codeceptjs
        tests: "./todomvc-tests/**_test.js"
        token: ${{ secrets.GITHUB_TOKEN }}
